name: Create Production Builds

jobs:
  build_web:
    type: generic
    steps:
      - name: 🏗 Setup build environment
        uses: actions/checkout@v3
      - name: 🔄 Switch to web platform
        run: node ./scripts/switch-platform.js web
      - name: 🏗 Build for web
        run: npm run build:web
      - name: Deploy to web server
        run: npm run deploy:web


