name: Development Build

on:
  push:
    tags:
      - "v*-dev*"

jobs:
  build:
    name: Build Android Development
    type: build
    env:
      APP_VERSION_FROM_TAG: ${{ github.ref_name }}
    params:
      platform: android
      profile: development

  summary:
    name: Build Summary
    type: doc
    after: [build]
    params:
      md: |
        ## Development Build Summary
        - Profile: `${{ needs.build.outputs.profile }}`
        - Version: `${{ needs.build.outputs.app_version || 'missing' }}`
        - Runtime version: `${{ needs.build.outputs.runtime_version || 'missing' }}`
        - Build version: `${{ needs.build.outputs.app_build_version || 'missing' }}`
        - Build ID: `${{ needs.build.outputs.build_id || 'missing' }}`
