name: Development Build

on:
  push:
    tags:
      - "v*-dev*"

jobs:
  build:
    name: Build Android Development
    type: build
    env:
      APP_VERSION_FROM_TAG: ${{ github.ref_name }}
    params:
      platform: android
      profile: development
