name: OTA Update

on:
  push:
    branches:
      - master
      - develop
      - preview

jobs:
  update_production:
    name: Update Production Channel
    type: generic
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish OTA update
        run: eas update --channel production --message "OTA ${{ github.sha }}" --non-interactive

  update_preview:
    name: Update Preview Channel
    type: generic
    if: ${{ github.ref == 'refs/heads/preview' }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish OTA update
        run: eas update --channel preview --message "OTA ${{ github.sha }}" --non-interactive

  update_development:
    name: Update Development Channel
    type: generic
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish OTA update
        run: eas update --channel development --message "OTA ${{ github.sha }}" --non-interactive
