name: Preview Build

on:
  push:
    tags:
      - "v*-rc*"
      - "v*-preview*"

jobs:
  build:
    name: Build Android Preview
    type: build
    env:
      APP_VERSION_FROM_TAG: ${{ github.ref_name }}
    params:
      platform: android
      profile: preview
